os:
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode9.1
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
  - printf "import Files\n\nlet testResources = try! Folder(path: \"$PWD/Tests/StyleSyncTests/Resources\")\n" > Tests/StyleSyncTests/Resources/Resources.swift
  - swift build
  - swift test
notifications:
  email: false
