language: objective-c
osx_image: xcode9.1
script:
  - swift build
  - swift build -X
  - swift test
before_install:
  - export SWIFT_VERSION=swift-4.0.2-RELEASE
  - curl -O https://swift.org/builds/development/xcode/${SWIFT_VERSION}/${SWIFT_VERSION}-osx.pkg
  - sudo installer -pkg ${SWIFT_VERSION}-osx.pkg -target /
  - export TOOLCHAINS=swift
notifications:
  email: false